import { URL } from "url"
import { default as fetch, Response } from "node-fetch"
import { default as toDocUpdate, setFetch } from "../src/GovUkDocFetcher"
import { createReadStream, readFileSync } from "fs";


describe("gov.uk doc fetcher", () => {
    it("fetches a doc and creates the DocUpdate", () => {
        const content = createReadStream("test/data/EU Exit secondary legislation laid with impacts on local government - GOV.UK.html")
        const mockFetch = (jest.fn((input: RequestInfo, init?: RequestInit) => {
            return Promise.resolve(new Response(content))
        }))
        setFetch(mockFetch as any as typeof fetch)
        const change = {
            url: new URL("https://www.gov.uk/government/publications/international-agreements-if-the-uk-leaves-the-eu-without-a-deal"),
            summary: "5:03pm, 4 April 2019: Updates made to the following agreements:Moldova Air Services Arrangement, Bosnia and Herzegovina Air Services Arrangement, Serbia Air Services Arrangement, Republic of North Macedonia Air Services Arrangement, Hague 2007, Hague 2005, INTERBUS, UK-US Agreement on Mutual Recognition, UK – Switzerland Trade Agreement, Norway and Iceland Trading Arrangements, UK-US Marine Mutual Recognition Agreement, Vine and Wine, Indonesia FLEGT, EU-Armenia Comprehensive and Enhanced Partnership Agreement’, Partnership and Cooperation Agreement between the European Communities and the Republic of Azerbaijan, Political Dialogue and Cooperation Agreement between the European Union and the Republic of Cuba, Partnership and Cooperation Agreement between the European Union and the Republic of Iraq, Strategic Partnership Agreement Between the European Union and Japan, Enhanced Partnership and Cooperation Agreement between the European Union and the Republic of Kazakhstan, EU-Singapore Partnership and Cooperation Agreement (ESPCA), Partnership and Cooperation Agreement between the EU and Turkmenistan (PCA), Parternship and Cooperation Agreement establishing a partnership between the European Communities and the Republic of Uzbekistan, EU-Armenia Comprehensive and Enhanced Partnership Agreement’, Partnership and Cooperation Agreement between the European Communities and the Republic of Azerbaijan, Political Dialogue and Cooperation Agreement between the European Union and the Republic of Cuba, Partnership and Cooperation Agreement between the European Union and the Republic of Iraq, Strategic Partnership Agreement Between the European Union and Japan, Enhanced Partnership and Cooperation Agreement between the European Union and the Republic of Kazakhstan, EU-Singapore Partnership and Cooperation Agreement (ESPCA), Partnership and Cooperation Agreement between the EU and Turkmenistan (PCA), Parternship and Cooperation Agreement establishing a partnership between the European Communities and the Republic of Uzbekistan, North Atlantic Ocean"
        }

        const docUpdate = toDocUpdate(change)
        expect(mockFetch.mock.calls[0][0]).toBe(change.url.toString())
        return expect(docUpdate).resolves.toEqual({
            path: "/government/publications/international-agreements-if-the-uk-leaves-the-eu-without-a-deal",
            content: readFileSync("test/data/EU Exit secondary legislation laid with impacts on local government - GOV.UK.content.html", { encoding: "UTF-8" }),
            changeMessage: "5:03pm, 4 April 2019: Updates made to the following agreements:Moldova Air Services Arrangement, Bosnia and Herzegovina Air Services Arrangement, Serbia Air Services Arrangement, Republic of North Macedonia Air Services Arrangement, Hague 2007, Hague 2005, INTERBUS, UK-US Agreement on Mutual Recognition, UK – Switzerland Trade Agreement, Norway and Iceland Trading Arrangements, UK-US Marine Mutual Recognition Agreement, Vine and Wine, Indonesia FLEGT, EU-Armenia Comprehensive and Enhanced Partnership Agreement’, Partnership and Cooperation Agreement between the European Communities and the Republic of Azerbaijan, Political Dialogue and Cooperation Agreement between the European Union and the Republic of Cuba, Partnership and Cooperation Agreement between the European Union and the Republic of Iraq, Strategic Partnership Agreement Between the European Union and Japan, Enhanced Partnership and Cooperation Agreement between the European Union and the Republic of Kazakhstan, EU-Singapore Partnership and Cooperation Agreement (ESPCA), Partnership and Cooperation Agreement between the EU and Turkmenistan (PCA), Parternship and Cooperation Agreement establishing a partnership between the European Communities and the Republic of Uzbekistan, EU-Armenia Comprehensive and Enhanced Partnership Agreement’, Partnership and Cooperation Agreement between the European Communities and the Republic of Azerbaijan, Political Dialogue and Cooperation Agreement between the European Union and the Republic of Cuba, Partnership and Cooperation Agreement between the European Union and the Republic of Iraq, Strategic Partnership Agreement Between the European Union and Japan, Enhanced Partnership and Cooperation Agreement between the European Union and the Republic of Kazakhstan, EU-Singapore Partnership and Cooperation Agreement (ESPCA), Partnership and Cooperation Agreement between the EU and Turkmenistan (PCA), Parternship and Cooperation Agreement establishing a partnership between the European Communities and the Republic of Uzbekistan, North Atlantic Ocean"
        })
    })
})
