apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitgov-repo-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitgov
spec:
  selector:
    matchLabels:
      app: gitgov
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitgov
    spec:
      containers:
      - name: gitgov-smtp-receiver
        image: rg.nl-ams.scw.cloud/njkonl/gitgov:0.1.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "80Mi"
            cpu: "50m"
        ports:
        - containerPort: 25
          hostPort: 25
        volumeMounts:
          - mountPath: "/repomount"
            name: repo
          - mountPath: /root/.ssh
            name: ssh-key
            readOnly: true
        env:
          - name: REPODIR
            value: /repomount/repo
      initContainers:
      - name: prepare-repo
        image: rg.nl-ams.scw.cloud/njkonl/clone-repo:0.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "80Mi"
            cpu: "10m"
        volumeMounts:
          - mountPath: "/repomount"
            name: repo
          - mountPath: /root/.ssh
            name: ssh-key
            readOnly: true
        terminationMessagePolicy: FallbackToLogsOnError
        args:
          - /repomount/repo
          - git@github.com:platy/gitgovuk.git
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: repo
          persistentVolumeClaim:
            claimName: gitgov-repo-claim
        - name: ssh-key
          secret:
            secretName: gitgov-repo-sshcreds
            defaultMode: 0600
          
